# Generated by Django 4.2.5 on 2023-12-19 06:39

from django.db import migrations, models
import posts.models.post


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_user_alter_postbookmark_user_bookmark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='videoUrl',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.post.upload_image),
        ),
        migrations.AddField(
            model_name='post',
            name='type_post',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('IMAGE', 'IMAGE')], default='VIDEO', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.post.upload_image),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('DRAFT', 'DRAF')], default='PUBLIC', max_length=10),
        ),
    ]
