# Generated by Django 4.2.5 on 2023-12-21 15:23

from django.db import migrations, models
import posts.models.post


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_thumb',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.post.upload_image),
        ),
    ]
