# Generated by Django 4.2.5 on 2023-12-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_video_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postimage',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
