# Generated by Django 4.2.5 on 2023-12-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='likes',
            new_name='num_fans',
        ),
        migrations.AddField(
            model_name='user',
            name='num_following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='num_posts',
            field=models.IntegerField(default=0),
        ),
    ]
